# -*- coding: utf-8 -*-
"""clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JV8rsN57TsG7aIevMgufhb-cESRrapBw

https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"
df = pd.read_csv(url)
df.head()

#limpieza de datos
clientes = df.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
    clientes[col] = clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

clientes['email'] = clientes['email'].str.lower()

clientes['fecha_nacimiento'] = pd.to_datetime(clientes['fecha_nacimiento'], errors='coerce')

clientes = clientes.drop_duplicates()

#Separar datos válidos y rechazados
validos = clientes[
    clientes['nombre'].notna() &
    clientes['email'].notna()
].copy()

rechazados = clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

#motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#Exportar archivos
validos.to_csv("clientes_curated.csv", index=False)

rechazados.to_csv("clientes_rejects.csv", index=False)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

pd.read_sql(
"SELECT to_char(fecha_nacimiento,'YYYY-MM-DD') FROM clientes_curated LIMIT 10",
engine
)