# -*- coding: utf-8 -*-
"""etl_Siniestros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146DWDxuZgwHEbmJFUrPP7FW2qUfAZ21W

https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"
df = pd.read_csv(url)
df.head()

#limpieza de datos
siniestros = df.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

siniestros['fecha_siniestro'] = pd.to_datetime(siniestros['fecha_siniestro'], errors='coerce')

siniestros['monto_siniestro'] = siniestros['monto_siniestro'].replace(['N/A', '-'], pd.NA)
siniestros['monto_siniestro'] = siniestros['monto_siniestro'].astype(str).str.replace(",", "", regex=False)
siniestros['monto_siniestro'] = pd.to_numeric(siniestros['monto_siniestro'], errors='coerce')

siniestros['estado'] = siniestros['estado'].str.upper().str.strip()

siniestros = siniestros.drop_duplicates()

#Separar datos válidos y rechazados
validos = siniestros[
    siniestros['fecha_siniestro'].notna() &
    siniestros['monto_siniestro'].notna() &
    siniestros['estado'].notna()
].copy()

rechazados = siniestros[
    siniestros['fecha_siniestro'].isna() |
    siniestros['monto_siniestro'].isna() |
    siniestros['estado'].isna()
].copy()

#motivo de rechazo
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_vacia")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_vacio")

    if pd.isna(row['estado']):
        motivos.append("estado_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#Exportar archivos
validos.to_csv("Siniestros_curated.csv", index=False)

rechazados.to_csv("siniestros_rejects.csv", index=False)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql('siniestros_curated', engine, if_exists='append', index=False)

rechazados.to_sql('siniestros_rejects', engine, if_exists='append', index=False)

pd.read_sql("SELECT * FROM siniestros_curated LIMIT 10", engine)