# -*- coding: utf-8 -*-
"""etl_Corredores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQeTDrMvbrA13vK-3ueJB7TUTkSAU7ik

https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"
df = pd.read_csv(url)
df.head()

#Limpieza dr datos
corredores = df.copy()

corredores.columns = corredores.columns.str.strip().str.lower()

for col in corredores.select_dtypes(include='object').columns:
    corredores[col] = corredores[col].astype(str).str.strip()

corredores = corredores.replace(r'^\s*$', pd.NA, regex=True)

corredores['nombre'] = corredores['nombre'].str.title()
corredores['zona'] = corredores['zona'].str.title()
corredores['nivel'] = corredores['nivel'].str.title()

corredores['anios_experiencia'] = pd.to_numeric(corredores['anios_experiencia'], errors='coerce')

corredores = corredores.drop_duplicates()

#Separar datos válidos y rechazados
validos = corredores[
    corredores['nombre'].notna() &
    corredores['zona'].notna() &
    corredores['nivel'].notna() &
    corredores['anios_experiencia'].notna()
].copy()

rechazados = corredores[
    corredores['nombre'].isna() |
    corredores['zona'].isna() |
    corredores['nivel'].isna() |
    corredores['anios_experiencia'].isna()
].copy()

#motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['zona']):
        motivos.append("zona_vacio")

    if pd.isna(row['nivel']):
        motivos.append("nivel_vacio")

    if pd.isna(row['anios_experiencia']):
        motivos.append("experiencia_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#Exportar archivos
validos.to_csv("corredores_curated.csv", index=False)
rechazados.to_csv("corredores_rejects.csv", index=False)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql('corredores_curated', engine, if_exists='append', index=False)

rechazados.to_sql('corredores_rejects', engine, if_exists='append', index=False)

pd.read_sql("SELECT * FROM corredores_curated LIMIT 10", engine)