# -*- coding: utf-8 -*-
"""etl_aseguradoras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15t5VbF23HrNPoKs4wgojDmwl5283kr1P

https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"
df = pd.read_csv(url)
df.head()

#Limpieza de datos
aseguradoras = df.copy()

aseguradoras.columns = aseguradoras.columns.str.strip().str.lower()

for col in aseguradoras.select_dtypes(include='object').columns:
    aseguradoras[col] = aseguradoras[col].astype(str).str.strip()

aseguradoras = aseguradoras.replace(r'^\s*$', pd.NA, regex=True)

aseguradoras = aseguradoras.drop_duplicates()
aseguradoras['pais'] = aseguradoras['pais'].str.upper().str.replace(" ", "")

#separacion de datos
validos = aseguradoras[
    aseguradoras['nombre'].notna() &
    aseguradoras['pais'].notna() &
    aseguradoras['rating_riesgo'].notna()
].copy()

rechazados = aseguradoras[
    aseguradoras['nombre'].isna() |
    aseguradoras['pais'].isna() |
    aseguradoras['rating_riesgo'].isna()
].copy()

#motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['pais']):
        motivos.append("pais_vacio")

    if pd.isna(row['rating_riesgo']):
        motivos.append("rating_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#exportacion del archivo
validos.to_csv("aseguradoras_curated.csv", index=False)

rechazados.to_csv("aseguradoras_rejects.csv", index=False)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"

engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

pd.read_sql(
    "SELECT * FROM aseguradoras_curated LIMIT 10",
    engine
)