# -*- coding: utf-8 -*-
"""etl_Polizas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7tKRyGGK86PhyqR436BAWnV7e-bOkvH

https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"
df = pd.read_csv(url)
df.head()

#Limpieza de datos
polizas = df.copy()

polizas.columns = polizas.columns.str.strip().str.lower()

for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].astype(str).str.strip()

polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)

polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce')

for col in ['prima', 'comision', 'monto_asegurado']:
    polizas[col] = polizas[col].replace(['N/A', '-'], pd.NA)
    polizas[col] = polizas[col].astype(str).str.replace(",", "", regex=False)
    polizas[col] = pd.to_numeric(polizas[col], errors='coerce')

polizas = polizas.drop_duplicates()

#Separar datos válidos y rechazo
validos = polizas[
    polizas['fecha_emision'].notna() &
    polizas['prima'].notna() &
    polizas['monto_asegurado'].notna()
].copy()

rechazados = polizas[
    polizas['fecha_emision'].isna() |
    polizas['prima'].isna() |
    polizas['monto_asegurado'].isna()
].copy()

#motivo de rechazo
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_vacia")

    if pd.isna(row['prima']):
        motivos.append("prima_vacia")

    if pd.isna(row['monto_asegurado']):
        motivos.append("monto_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#Exportar archivos
validos.to_csv("Polizas_curated.csv", index=False)

rechazados.to_csv("Polizas_rejects.csv", index=False)

df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql('polizas_curated', engine, if_exists='append', index=False)

rechazados.to_sql('polizas_rejects', engine, if_exists='append', index=False)

pd.read_sql("SELECT * FROM polizas_curated LIMIT 10", engine)