# -*- coding: utf-8 -*-
"""etl_Tipo_Seguros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rONrmqumSqJVc-63IndTJWT6boN9BZr1

https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv
"""

import pandas as pd

url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"
df = pd.read_csv(url)
df.head()

#Limpieza de datos
tipo_seguro = df.copy()

tipo_seguro.columns = tipo_seguro.columns.str.strip().str.lower()

for col in tipo_seguro.select_dtypes(include='object').columns:
    tipo_seguro[col] = tipo_seguro[col].astype(str).str.strip()

tipo_seguro = tipo_seguro.replace(r'^\s*$', pd.NA, regex=True)

tipo_seguro['tipo'] = tipo_seguro['tipo'].str.title()
tipo_seguro['categoria'] = tipo_seguro['categoria'].str.title()

tipo_seguro['tipo'] = tipo_seguro['tipo'].replace({
    'Educaciã³n': 'Educación',
    'Agrã­cola': 'Agrícola'
})

tipo_seguro['riesgo_base'] = tipo_seguro['riesgo_base'].replace(['N/A', '-'], pd.NA)
tipo_seguro['riesgo_base'] = pd.to_numeric(tipo_seguro['riesgo_base'], errors='coerce')

tipo_seguro = tipo_seguro.drop_duplicates()

#Separacion de datos valios y Rechazados
validos = tipo_seguro[
    tipo_seguro['tipo'].notna() &
    tipo_seguro['categoria'].notna() &
    tipo_seguro['riesgo_base'].notna()
].copy()

rechazados = tipo_seguro[
    tipo_seguro['tipo'].isna() |
    tipo_seguro['categoria'].isna() |
    tipo_seguro['riesgo_base'].isna()
].copy()

#motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['tipo']):
        motivos.append("tipo_vacio")

    if pd.isna(row['categoria']):
        motivos.append("categoria_vacio")

    if pd.isna(row['riesgo_base']):
        motivos.append("riesgo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

#exportacion del archivo
validos.to_csv("tipo_seguro_curated.csv", index=False)

rechazados.to_csv("tipo_seguro_rejects.csv", index=False)

#revision de datos
df.shape
df.columns
df.info()
df.isnull().sum()

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"

engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

validos.to_sql(
    'tipo_seguro_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'tipo_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

pd.read_sql(
    "SELECT * FROM tipo_seguro_curated LIMIT 10",
    engine
)